### ISSUE TITLE
cant update

### ISSUE THREAD

**Issue by MedicinalPsycho** [liurui39660/PayDay2.Mod#1]
wenn i try to update it through the ingame menu, useing superblt it says: "Mercerial or git version control are in use for this mod, update blocked"

im a noob to payday 2 mods this is the first time ive updates a mod so .... yea

**Comment by liurui39660** [comment]
Ah ... which mod? Maybe I forgot to delete `.git` before uploading.

**Comment by MedicinalPsycho** [comment]
better graze

**Comment by liurui39660** [comment]
I can't find any issue from the zip file. Can you try to delete the `mods/Better Graze`, then download it again? (this link: https://github.com/liurui39660/PayDay2.Mod/releases/download/1.3.0-BG/Better.Graze.zip)

**Comment by MedicinalPsycho** [comment]
ok i re-downloaded the mod its working and no longer needs a update 

thanks for the help, i love the mod
